import React from 'react'
import './CSS/AboutUs.css'


const AboutUS = () => {
  return (
    <div className='about'>
        <h1>THE ORIGINS</h1>
        <p>The label is based in Timisoara, Romania, founded in 2018 by Nodis Ionut & Stanila Luis <br />

The two creatives, born and raised in West Romania, founded the brand “CREATEDBY” out of a fueling passion for creation. <br />

The brand serves the purpose of filling the gap between luxury & accessibility. Taking such an untouchable thing like luxury and making it available for everyone who wants to experience true luxury in fashion. <br />

The Timisoara based brand, represents the misfits, the abnormals, the non- conformists, the ones who don’t fit in, the ones who are in search for freedom in creation... meaningful expression, we are giving an “abandoned” generation a voice that can be heard. <br />

Street mixed with vision & luxury, come together to form a label that shouldn’t even exist in society's norms. Two kids who shouldn’t even call themselves “designers”, two kids who refuse to be labeled and put in a box, simply... WE ARE CREATIVES. <br />

Within us, luxury & streetwear come together to create a voice for the YOUth. <br />

Our end goal is to build something bigger & deeper than all of us. We strive to make people feel deep emotion, to understand problems that outcast us as a species, deeper than us. <br />

We strive to make people feel something...without saying anything.</p>

<h1>Energy Use</h1>

<p>The power used to run textile mills is significant. It is important to understand how the energy consumed is generated, especially as a large amount of fabric production takes place in developing countries. The use of regional energy sources, such as solar, wind, water and others should be encouraged, especially in the production of sustainable fibre sources, such as organic cotton or recycled polyester. Manufactured fibre consumes large amounts of energy in production, but little water. Fibre production is very efficient, however. <br />
The emissions generated by crop chemicals and manufactured fibre production are unhealthy to breathe. <br />
Crop emissions are unregulated by clean air monitors, while manufactured *fibre-mill ( *the factories that turn fibre into finished fabric)  emissions are controlled. <br />
All the information above is a little generic, let's do a case study instead. <br />
Cotton in it's raw state <br />
It's uses from casual T-Shirts to distressed denim jeans, cotton continues to be one of the most important materials on earth for everyday use. It's popularity has been long-standing - with fragments of cotton fabric found in the Indus Valley  Civilisation since 6000 - 5000 BC. <br />
Cotton is the most popular fibre in the world, it is a seed fibre grown as a protective case around the seed of the cotton plant. Known to be the most popular natural fibre in the world, it is soft and fluffy to the touch and is usually off-white in colour. <br />
Conventional cotton requires extremely high moisture levels, resulting from rainfall or irrigation during the growing season, and a warm, dry season during the picking period. Picked cotton will go through ginning to separate the fibres from the seeds. Significant ecological and social impact caused by large-scale intensive production is a great concern in the industry. <br />
Annual cotton production across the globe reaches as high as 25.000.000.00 Tones of cotton produced every year, and 2.5% off all earth's arable land is accounted for cotton production <br />
</p>
      
    </div>
    
  )
}

export default AboutUS